name: AI Code Reviewer

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

permissions:
  write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: cheton/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: "https://pullrequest-review.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2024-08-01-preview"
          AZURE_OPENAI_DEPLOYMENT: "gpt-4"
          AZURE_OPENAI_API_VERSION: "2024-04-09"
          exclude: "**/*.md, **/*.yaml" # Optional: exclude patterns separated by commas
